services:
  - type: web
    name: my-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    environment:
      python_version: 3.9.12
  ####ffff